---
services:
  - type: web
    name: tienda-server
    env: node
    plan: free
    database:
      name: tienda-db
      property: connectionString
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: do3b7nz6y
      - key: CLOUDINARY_API_KEY
        value: 279456539672662
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
databases:
  - name: tienda-db
    databaseName: tienda_db
    user: tienda_user
    plan: free
